---
- name: Install docker on a Centos 7 machine
  hosts: all
  become: yes
  become_method: su
  tasks:
    - block:
        - parted: device=/dev/sda2 unit=GiB
          register: sda2_info
        - debug:
            msg: '{{ sda2_info.disk.size }}'
        - debug:
            msg: "{{ sda2_info.disk.size }} greater than 40"
          when: " sda2_info.disk.size  > 40"
        - debug:
            msg: "{{ sda2_info.disk.size }} less than 40"
          when: " sda2_info.disk.size  < 40"
    - name: Install pre-requisite packages
      yum:
        name: "{{item}}"
        state: latest
      loop:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    - name: Add Docker CE repo
      get_url:
       url: https://download.docker.com/linux/centos/docker-ce.repo
       dest: /etc/yum.repos.d/docker-ce.repo
    - name: Install Docker
      yum: name=docker-ce state=latest
    - name: Start and enable the Docker daemon
      service: name=docker state=started enabled=yes
    - name: Expose Api
      lineinfile: 
        path: /lib/systemd/system/docker.service 
        regexp: '^(.*)ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock(.*)$' 
        line: 'ExecStart=/usr/bin/dockerd -H fd:// -H tcp://0.0.0.0:4243 --containerd=/run/containerd/containerd.sock'
        backrefs: yes
    - name: Reload Port Api
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: docker
    - name: Verify Api Connection
      shell: ps -ef|grep docker
      register: output
    - debug: msg="{{ output.stdout }}"
    - name: Install firewalld
      yum:
        name: firewalld
        state: latest
      notify:
        - start firewalld
    - name: start firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
      become: yes
    - name: enable 2376
      firewalld:
        zone: public
        port: "{{item}}"
        permanent: true
        state: enabled
      become: yes
      loop:
      - 2376/tcp
      - 2377/tcp
      - 7946/tcp
      - 80/tcp
      - 7946/udp
      - 4789/udp
    - name: reload service firewalld
      systemd:
        name: firewalld
        state: reloaded
    - name: install docker on localhost 
      yum:
        name: "{{item}}"
        state: latest
      loop:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2

    
