---
- hosts: localhost
  become: yes
  connection: local
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: Install pre-requisite packages
      apt:
        name: docker
        state: latest
    - name: Start and enable the Docker daemon
      service: name=docker state=started enabled=yes
    - name: Install Firewall
      apt:
        name: ufw
        state: latest
    - name: Port Enable Firewall TCP
      ufw:
        rule: allow
        port: "{{item}}"
        proto: tcp
      become: yes
      loop:
      - "2376"
      - "2377"
      - "7946"
      - "80"
      - "22"
    - name: Port Enable Firewall UDP
      ufw:
        rule: allow
        port: "{{item}}"
        proto: udp
      become: yes
      loop:
      - "7946"
      - "4789"
    - name: Enable Firewall daemon
      ufw:
        state: enabled
    - name: Reload Firewall daemon
      ufw:
        state: reloaded
    - name: Init Master Node 
      docker_swarm:
        state: present 
        advertise_addr: 192.168.33.1
    - name: Check Node
      shell: docker node ls
      register: output
    - debug: msg="{{ output.stdout }}"
    - name: check info 
      shell: docker info
      register: output
    - debug: msg="{{ output.stdout }}"
    - name: get token
      shell: docker swarm join-token manager
      register: token
    - name: Deploy Service from local machine 
      shell: docker service create -p 80:80 --name webservice --replicas 2 nginx
    - name: show service state
      shell: docker service ps webservice
      register: ps
    - debug: msg="{{ ps.stdout }}"
    - name: verify it works normally
      shell: curl 192.168.0.105
      register: s1
    - debug: msg="{{ s1.stdout }}"


