- name: Deploy Service Swarm on Master Node
  hosts: localhost
  connection: local
  become: true
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: verify server1 works normally
      shell: curl {{ hostvars[groups['servers'][0]].ansible_host }}
      register: s1
    - debug: msg="{{ s1.stdout }}"
    - name: verify server2 works normally
      shell: curl {{ hostvars[groups['servers'][1]].ansible_host }}
      register: s2
    - debug: msg="{{ s2.stdout }}"