- name: Swarm on Master Node
  hosts: localhost
  connection: local
  become: true
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: save in variable ipv4 advertise_addr
      shell: ip addr list eth9 |grep "inet " |cut -d' ' -f6|cut -d/ -f1
      register: adv
    - debug: msg="{{ adv.stdout }}"
    - name: Init Master Node 
      shell: echo "{{adv.stdout}}"
    - debug: msg="{{adv.stdout}}"