- name: Deploy Service Swarm on Master Node
  hosts: localhost
  connection: local
  become: true
  vars:
    ansible_python_interpreter: /bin/python3
  tasks:
    - name: Deploy Service from local machine 
      shell: docker service create -p 80:80 --name webservice --replicas 2 nginx
    - name: show service state
      shell: docker service ps webservice
      register: ps
    - debug: msg="{{ ps.stdout }}"
    - name: verify it works normally server1
      shell: curl 192.168.0.105
      register: s1
    - debug: msg="{{ s1.stdout }}"
    - name: verify it works normally server2
      shell: curl 192.168.0.106
      register: s1
    - debug: msg="{{ s1.stdout }}"